development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_dev
  pool: 5
  username: pgadmin
  password: pgadmin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_test
  pool: 5
  username: pgadmin
  password: pgadmin
  host: localhost
